// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhoaujtxtiodbhenpmxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlob2F1anR4dGlvZGJoZW5wbXhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NDI5NDgsImV4cCI6MjA3MDExODk0OH0.mva03MltQGo_s4znMf_NXroUb-Ef1syst9gZ5fUwJJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});